---
nerdctl_ver: 2.0.4

nerdctl_install_dir: /usr/local/bin

# https://github.com/containerd/nerdctl/releases
# https://github.com/containerd/nerdctl/releases/download/v2.0.4/nerdctl-2.0.4-linux-amd64.tar.gz
nerdctl_download_url: 'https://github.com/containerd/nerdctl/releases/download/v{{ nerdctl_ver }}/nerdctl-{{ nerdctl_ver }}-linux-amd64.tar.gz'

# https://github.com/containerd/nerdctl/releases/download/2.0.4/SHA256SUMS
nerdctl_checksum: sha256:2f9d22179868db4f0a1daf2fd65f58a24f8a78efd2d9b17659f56bcdce85efd0

nerdctl_force_update: false