version: 3

silent: true

vars:
  # Common across tasks
  CONFIG_DIR:          "/root/.oci"
  DEPLOY_DIR:          "/opt/EVOCLOUD/Terraform/oci/deployment"
  KEYS_DIR:            "/opt/EVOCLOUD/Keys"
  BUILD_CMD:           "terragrunt run-all apply --non-interactive --queue-include-external -auto-approve"
  CLUSTER_DESTROY_CMD: "terragrunt apply --non-interactive -auto-approve"
  DESTROY_CMD:         "terragrunt destroy --non-interactive -auto-approve"


tasks:
  # Internal tasks that remove redundant code and simplifies logic
  # Internal tasks do not show up available task list.
  # SERVER is the server being operated on.
  # ACTION is BUILD_CMD or DESTROY_CMD
  vm-operation:
    internal: true
    cmds:
      - |
        cd {{.DEPLOY_DIR}}/{{.SERVER}}/ && \
        {{.ACTION}}  

  ###############################
  # Neutral/Dependency Tasks
  ###############################
  copy-files:
    # Task only runs if one or more status commands not satisfied"
    # Files: gcp-evocloud.pem, gcp-evocloud.pub, ansible-vault-pass.txt, secret-store.yml and root.hcl
    desc: "OCI: Copies files from mount directory inside container to their respective locations."
    status:
      - "ls -al /etc/pki/tls | grep oci_evocloud.pem"
      - "ls -al /etc/pki/tls | grep oci_evocloud.pub"
      - "ls -al Ansible/secret-vault | grep ansible-vault-pass.txt"
      - "ls -al Ansible/secret-vault | grep secret-store.yml"
    cmds:
      # The slash in front of the cp commands is required to prevent user from being prompted to confirm.
      # The cp command in rocky linux is aliased to cp -i.
      - \cp {{.MNTDIR}}/oci/config {{.CONFIG_DIR}}
      - \cp {{.MNTDIR}}/oci/config {{.KEYS_DIR}}
      - \cp {{.MNTDIR}}/oci/*.pem /etc/pki/tls
      - \cp {{.MNTDIR}}/oci/*.pub /etc/pki/tls
      - \cp {{.MNTDIR}}/oci/ansible-vault-pass.txt {{.MNTDIR}}/oci/secret-store.yml Ansible/secret-vault
      - \cp {{.MNTDIR}}/oci/root.hcl {{.DEPLOY_DIR}}
      - chmod 0600 /etc/pki/tls/*.pem
      - chmod 0644 /etc/pki/tls/*.pub

  ###############################
  # Build Tasks
  ###############################
  build-evo-master:
    desc: "OCI: Build evo-master Server"
    deps: [copy-files]
    cmds:
      - echo "OCI':' Building evo-master"
      - task: vm-operation
        vars:
          SERVER: server-01-dmz-deployer
          ACTION: "{{.BUILD_CMD}}"

  build-evo-idp:
    desc: "OCI: Build EvoCloud IdM Server"
    deps: [copy-files]
    cmds:
      - echo "OCI':' Building EvoCloud IdM Server"
      - task: vm-operation
        vars:
          SERVER: server-02-admin-idam-helper
          ACTION: "{{.BUILD_CMD}}"

  build-evo-idpr:
    desc: "OCI: Build EvoCloud IdM Replica Server"
    deps: [copy-files]
    cmds:
      - echo "OCI':' Building EvoCloud IdM Replica Server"
      - task: vm-operation
        vars:
          SERVER: server-03-admin-idam_replica-helper
          ACTION: "{{.BUILD_CMD}}"

  build-evo-rdp:
    desc: "OCI: Build EvoCloud Remote Desktop Server"
    deps: [copy-files]
    cmds:
      - echo "OCI':' Building EvoCloud Remote Desktop Server"
      - task: vm-operation
        vars:
          SERVER: server-dmz-rdp-helper
          ACTION: "{{.BUILD_CMD}}"

  build-evo-cluster-std:
    desc: "OCI: Build EvoCloud Single Node Cluster"
    deps: [copy-files]
    cmds:
      - echo "OCI':' Building EvoCloud Single Node Kube Cluster"
      - task: vm-operation
        vars:
          SERVER: cluster-talos-standalone-helper
          ACTION: "{{.BUILD_CMD}}"

  build-evo-cluster-mgr:
    desc: "OCI: Build EvoCloud Full Kube Cluster"
    deps: [copy-files]
    cmds:
      - echo "OCI':' Building Full EvoCloud Kube Cluster"
      - task: vm-operation
        vars:
          SERVER: cluster-admin-talos-helper
          ACTION: "{{.BUILD_CMD}}"

  build-evo-code:
    desc: "OCI: Build EvoCloud Code Server"
    deps: [copy-files]
    cmds:
      - echo "OCI':' Building EvoCloud Code Server"
      - task: vm-operation
        vars:
          SERVER: server-backend-evocode-helper
          ACTION: "{{.BUILD_CMD}}"

  build-evo-code-runner:
    desc: "OCI: Build EvoCloud Code Runner Server"
    deps: [copy-files]
    cmds:
      - echo "OCI':' Building EvoCloud Code Runner Server"
      - task: vm-operation
        vars:
          SERVER: server-backend-evocode-runner-helper
          ACTION: "{{.BUILD_CMD}}"

  build-evo-harbor:
    desc: "OCI: Build EvoCloud Harbor Server"
    deps: [copy-files]
    cmds:
      - echo "OCI':' Building EvoCloud Harbor Server"
      - task: vm-operation
        vars:
          SERVER: server-backend-evoharbor-helper
          ACTION: "{{.BUILD_CMD}}"

  build-evo-vcd:
    desc: "OCI: Build EvoCloud Virtual Cloud Desktop Server"
    deps: [copy-files]
    cmds:
      - echo "OCI':' Building EvoCloud Virtual Cloud Desktop Server"
      - task: vm-operation
        vars:
          SERVER: server-dmz-vcd-helper
          ACTION: "{{.BUILD_CMD}}"

  ###############################
  # Destroy Tasks
  ###############################
  destroy-evo-master:
    desc: "OCI: Destroy evo-master"
    deps: [copy-files]
    cmds:
      - echo "OCI':' Destroying evo-master"
      - task: vm-operation
        vars:
          SERVER: server-01-dmz-deployer
          ACTION: "{{.DESTROY_CMD}}"

  destroy-evo-idp:
    desc: "OCI: Destroy EvoCloud IdM Server"
    deps: [copy-files]
    cmds:
      - echo "OCI':' Destroying EvoCloud IdM Server"
      - task: vm-operation
        vars:
          SERVER: server-02-admin-idam
          ACTION: "{{.DESTROY_CMD}}"

  destroy-evo-idpr:
    desc: "OCI: Destroy EvoCloud IdM Replica Server"
    deps: [copy-files]
    cmds:
      - echo "OCI':' Destroying EvoCloud IdM Replica Server"
      - task: vm-operation
        vars:
          SERVER: server-03-admin-idam_replica
          ACTION: "{{.DESTROY_CMD}}"

  destroy-evo-rdp:
    desc: "OCI: Destroy EvoCloud Remote Desktop Server"
    deps: [copy-files]
    cmds:
      - echo "OCI':' Destroying EvoCloud Remote Desktop Server"
      - task: vm-operation
        vars:
          SERVER: server-dmz-rdp
          ACTION: "{{.DESTROY_CMD}}"



  destroy-evo-cluster-std:
    desc: "OCI: Destroy EvoCloud Single Node Kube Cluster"
    deps: [copy-files]
    cmds:
      - echo "OCI':' Destroying EvoCloud Single Node Kube Cluster"
      - task: vm-operation
        vars:
          SERVER: cluster-talos-standalone-helper-destroyer
          ACTION: "{{.CLUSTER_DESTROY_CMD}}"

  destroy-evo-cluster-mgr:
    desc: "OCI: Destroy EvoCloud Full  Kube Cluster"
    deps: [copy-files]
    cmds:
      - echo "OCI':' Destroying EvoCloud Full Kube Cluster"
      - task: vm-operation
        vars:
          SERVER: cluster-admin-talos-helper-destroyer
          ACTION: "{{.CLUSTER_DESTROY_CMD}}"

  destroy-evo-code:
    desc: "OCI: Destroy EvoCloud Code Server"
    deps: [copy-files]
    cmds:
      - echo "OCI':' Destroy EvoCloud Code Server"
      - task: vm-operation
        vars:
          SERVER: server-backend-evocode
          ACTION: "{{.DESTROY_CMD}}"

  destroy-evo-code-runner:
    desc: "OCI: Destroy EvoCloud Code Runner Server"
    deps: [copy-files]
    cmds:
      - echo "OCI':' Destroy EvoCloud Code Runner Server"
      - task: vm-operation
        vars:
          SERVER: server-backend-evocode-runner
          ACTION: "{{.DESTROY_CMD}}"

  destroy-evo-harbor:
    desc: "OCI: Destroy EvoCloud Harbor Server"
    deps: [copy-files]
    cmds:
      - echo "OCI':' Destory EvoCloud Harbor Server"
      - task: vm-operation
        vars:
          SERVER: server-backend-evoharbor
          ACTION: "{{.DESTROY_CMD}}"

  destroy-evo-vcd:
    desc: "OCI: Destroy EvoCloud Virtual Cloud Desktop Server"
    deps: [copy-files]
    cmds:
      - echo "OCI':' Destroying EvoCloud Virtual Cloud Desktop Server"
      - task: vm-operation
        vars:
          SERVER: server-dmz-vcd
          ACTION: "{{.DESTROY_CMD}}"