---
# renovate: datasource=github-releases depName=aquasecurity/trivy versioning=semver
trivy_version: '0.69.3'

# https://github.com/aquasecurity/trivy/releases/tag/v0.69.3
trivy_download_url: 'https://github.com/aquasecurity/trivy/releases/download/v{{ trivy_version }}/trivy_{{ trivy_version }}_Linux-64bit.rpm'

# https://github.com/aquasecurity/trivy/releases/download/v0.69.3/trivy_0.69.3_checksums.txt
# renovate: datasource=github-releases depName=aquasecurity/trivy packageName=trivy_<semver>_Linux-64bit.rpm
trivy_checksum: sha256:c3db5f38b213e6ff414acee023fe831df80eb5280baa15d3b5353b7c171e67b4
