---
# renovate: datasource=github-releases depName=aquasecurity/trivy versioning=semver
trivy_version: '0.73.0'

# https://github.com/aquasecurity/trivy/releases/tag/v0.73.0
# https://github.com/aquasecurity/trivy/releases/download/v0.73.0/trivy_0.73.0_Linux-64bit.rpm
trivy_download_url: 'https://github.com/aquasecurity/trivy/releases/download/v{{ trivy_version }}/trivy_{{ trivy_version }}_Linux-64bit.rpm'

# https://github.com/aquasecurity/trivy/releases/download/v0.73.0/trivy_0.73.0_checksums.txt
# renovate: datasource=github-releases depName=aquasecurity/trivy packageName=trivy_<semver>_Linux-64bit.rpm
trivy_checksum: 'sha256:d4bfd0fb81127e5b6e6ec1cd095c4806024d9f2310c96cb8e1ce6b07c012d2ef'
