---
#Source: https://kubernetes.io/docs/tasks/tools/install-kubectl/

- ansible.builtin.debug:
    msg: "################# STARTING ANSIBLE ROLE: app-kubectl ##################"

- name: Checking if kubectl already exist...
  ansible.builtin.stat:
    path: '{{ kubectl_install_dir }}/kubectl'
  changed_when: false
  become: true
  register: kubectl_binary

- when: "(not kubectl_binary.stat.exists) or (kubectl_force_update | bool)"
  block:
    - name: Installing kubectl binaries...
      ansible.builtin.unarchive:
        src: 'kubernetes-client-linux-amd64.tar.gz'
        dest: '/opt'
        mode: '0755'
        remote_src: false
      become: true

    - name: Staging kubectl binaries...
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: '0755'
        remote_src: false
      loop:
        - src: "/opt/kubernetes/client/bin/kubectl"
          dest: "{{ kubectl_install_dir }}"
        - src: "/opt/kubernetes/client/bin/kubectl-convert"
          dest: "{{ kubectl_install_dir }}"
      become: true

  always:
    - name: Removing kubectl detritius...
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - '/opt/kubernetes'
      become: true
      