---
#Source: https://kubernetes.io/docs/tasks/tools/install-kubectl/

- ansible.builtin.debug:
    msg: "################# STARTING ANSIBLE ROLE: app-kubectl ##################"

- name: Checking if kubectl already exist...
  ansible.builtin.stat:
    path: '{{ kubectl_install_dir }}/kubectl'
  changed_when: false
  become: true
  register: kubectl_binary

- when: "(not kubectl_binary.stat.exists) or (kubectl_force_update | bool)"
  block:
    - name: Downloading and install kubectl binary...
      ansible.builtin.get_url:
        url: '{{ kubectl_download_url }}'
        dest: '{{ kubectl_install_dir }}'
        mode: 0755
        checksum: '{{ kubectl_checksum }}'
      become: true
      