---
#Source: https://kubernetes.io/docs/tasks/tools/install-kubectl/

- ansible.builtin.debug:
    msg: "################# STARTING ANSIBLE ROLE: app-kubectl ##################"

- name: Checking if kubectl already exist...
  ansible.builtin.stat:
    path: '{{ kubectl_install_dir }}/kubectl'
  changed_when: false
  become: true
  register: kubectl_binary

- when: "(not kubectl_binary.stat.exists) or (kubectl_force_update | bool)"
  block:
    - name: Verifying kubectl client binary checksum...
      ansible.builtin.get_url:
        url: '{{ kubectl_download_url }}'
        dest: '/tmp'
        mode: '0644'
        checksum: '{{ kubectl_checksum }}'
      become: true

    - name: Installing kubectl...
      ansible.builtin.unarchive:
        src: '/tmp/kubernetes-client-linux-amd64.tar.gz'
        dest: '{{ kubectl_install_dir }}'
        mode: '0755'
        remote_src: yes
        extra_opts:
          - --strip-components=3
      become: true

  always:
    - name: Removing kubectl detritius...
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - '/tmp/kubernetes-client-linux-amd64.tar.gz'
      become: true
