---
#This playbook will deploy Goldilocks Resource Limit Recommender
#References:

- ansible.builtin.debug:
    msg: "########### STARTING ANSIBLE ROLE: kubeapp-vpa_goldilocks ##############"

- name: Creating directories for manifest files...
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ goldilocks_kubeapp_dir }}"

######################################################
#Deploying Goldilocks Resources
######################################################
- name: Staging Kubernetes manifests...
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ goldilocks_kubeapp_dir }}/{{ item }}"
  loop:
    - goldilocks-rset.yaml

- name: Deploying Kubernetes manifests...
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    src: "{{ item }}"
  loop:
    - "{{ goldilocks_kubeapp_dir }}/goldilocks-rset.yaml"
  register: goldilocks_deploy_result
  until: goldilocks_deploy_result is succeeded
  retries: 10
  delay: 30
