version: 3

silent: true

vars:
  # Common across tasks
  DEPLOY_DIR:          "/opt/EVOCLOUD/Terraform/gcp/deployment"
  GCLOUD_AUTH:         "gcloud auth activate-service-account --key-file"
  GCLOUD_EXPORT:       "export GOOGLE_APPLICATION_CREDENTIALS"
  KEYS_DIR:            "/opt/EVOCLOUD/Keys"
  BUILD_CMD:           "terragrunt run-all apply --non-interactive --queue-include-external -auto-approve"
  CLUSTER_DESTROY_CMD: "terragrunt apply --non-interactive -auto-approve"
  DESTROY_CMD:         "terragrunt destroy --non-interactive -auto-approve"


tasks:
  # Internal tasks that remove redundant code and simplifies logic
  # Internal tasks do not show up available task list.
  # SERVER is the server being operated on.
  # ACTION is BUILD_CMD or DESTROY_CMD
  vm-operation:
    internal: true
    cmds:
      - |
        {{.GCLOUD_AUTH}} {{.KEYS_DIR}}/{{.KEYFILE}} && \
        {{.GCLOUD_EXPORT}}={{.KEYS_DIR}}/{{.KEYFILE}} && \
        cd {{.DEPLOY_DIR}}/{{.SERVER}}/ && \
        {{.ACTION}}  

  ###############################
  # Neutral/Dependency Tasks
  ###############################
  copy-files:
    desc: "Copies files from /mnt inside container to their respective locations.
           Files: gcp-evocloud.pem, gcp-evocloud.pub, ansible-vault-pass.txt, secret-store.yml and root.hcl
           Task only runs if one or more status commands not satisfied"
    status:
      - "ls -al /etc/pki/tls | grep gcp-evocloud.pem"
      - "ls -al /etc/pki/tls | grep gcp-evocloud.pub"
      - "ls -al Ansible/secret-vault | grep ansible-vault-pass.txt"
      - "ls -al Ansible/secret-vault | grep secret-store.yml"
    cmds:
    # The slash in front of the cp commands is required to prevent user from being prompted to confirm.
    # The cp command in rocky linux is aliased to cp -i.
      - \cp {{.MNTDIR}}/gcp/*.json {{.KEYS_DIR}}
      - \cp {{.MNTDIR}}/*.pem /etc/pki/tls
      - \cp {{.MNTDIR}}/*.pub /etc/pki/tls
      - \cp {{.MNTDIR}}/ansible-vault-pass.txt {{.MNTDIR}}/secret-store.yml Ansible/secret-vault
      - \cp {{.MNTDIR}}/root.hcl {{.DEPLOY_DIR}}
      - chmod 0600 /etc/pki/tls/*.pem
      - chmod 0644 /etc/pki/tls/*.pub

  ###############################
  # Build Tasks
  ###############################
  build-evo-master:
    desc: "Deploys evo-master Server"
    deps: [copy-files]
    cmds:
      - echo "Deploying evo-master"
      - task: vm-operation
        vars:
            SERVER: server-01-dmz-deployer
            ACTION: "{{.BUILD_CMD}}"

  build-idm:
    desc: "Deploys IdM Server"
    deps: [copy-files]
    cmds:
      - echo "Deploying IdM Server"
      - task: vm-operation
        vars:
          SERVER: server-02-admin-idam-helper
          ACTION: "{{.BUILD_CMD}}"

  build-idm-replica:
    desc: "Deploys IdM Replica Server"
    deps: [copy-files]
    cmds:
      - echo "Deploying IdM Replica Server"
      - task: vm-operation
        vars:
          SERVER: server-03-admin-idam_replica-helper
          ACTION: "{{.BUILD_CMD}}"

  build-rdp:
    desc: "Deploys Remote Desktop Server"
    deps: [copy-files]
    cmds:
      - echo "Deploying Remote Desktop Server"
      - task: vm-operation
        vars:
          SERVER: server-dmz-rdp
          ACTION: "{{.BUILD_CMD}}"

  build-talos-single:
    desc: "Deploys Single Node Talos Cluster"
    deps: [copy-files]
    cmds:
      - echo "Deploying Talos Single Node Kube Cluster"
      - task: vm-operation
        vars:
          SERVER: cluster-talos-standalone-helper
          ACTION: "{{.BUILD_CMD}}"

  build-talos-cluster:
    desc: "Deploys Full Talos Cluster"
    deps: [copy-files]
    cmds:
      - echo "Deploying Full Talos Kube Cluster"
      - task: vm-operation
        vars:
          SERVER: cluster-admin-talos-helper
          ACTION: "{{.BUILD_CMD}}"

  ###############################
  # Destroy Tasks
  ###############################
  destroy-evo-master:
    desc: "Destroy evo-master"
    deps: [copy-files]
    cmds:
      - echo "Destroying evo-master"
      - task: vm-operation
        vars:
          SERVER: server-01-dmz-deployer
          ACTION: "{{.DESTROY_CMD}}"

  destroy-idm:
    desc: "Destroy IdM Server"
    deps: [copy-files]
    cmds:
      - echo "Destroying IdM Server"
      - task: vm-operation
        vars:
          SERVER: server-02-admin-idam
          ACTION: "{{.DESTROY_CMD}}"

  destroy-idm-replica:
    desc: "Destroy IdM Replica Server"
    deps: [copy-files]
    cmds:
      - echo "Destroying IdM Replica Server"
      - task: vm-operation
        vars:
          SERVER: server-03-admin-idam_replica
          ACTION: "{{.DESTROY_CMD}}"

  destroy-rdp:
    desc: "Destroy Remote Desktop Server"
    deps: [copy-files]
    cmds:
      - echo "Destroying Remote Desktop Server"
      - task: vm-operation
        vars:
          SERVER: server-dmz-rdp
          ACTION: "{{.DESTROY_CMD}}"

  destroy-talos-single:
    desc: "Destroy Talos Single Node Kube Cluster"
    deps: [copy-files]
    cmds:
      - echo "Destroying Talos Single Node Kube Cluster"
      - task: vm-operation
        vars:
          SERVER: cluster-talos-standalone-helper-destroyer
          ACTION: "{{.CLUSTER_DESTROY_CMD}}"

  destroy-talos-cluster:
    desc: "Destroy Full Talos Kube Cluster"
    deps: [copy-files]
    cmds:
      - echo "Destroying Full Talos Kube Cluster"
      - task: vm-operation
        vars:
          SERVER: cluster-admin-talos-helper-destroyer
          ACTION: "{{.CLUSTER_DESTROY_CMD}}"
