version: 3

tasks:
  gcloud-auth:
    desc: "Authenticates to gcloud so VMs and Kube cluster can be deployed"
    silent: true
    cmds:
      - gcloud auth activate-service-account --key-file "{{.MNTDIR}}/{{.KEYFILE}}"
      - export GOOGLE_APPLICATION_CREDENTIALS="{{.MNTDIR}}/{{.KEYFILE}}"

  deploy-talos-single:
    desc: "Deploys Single Node Talos Cluster"
    silent: true
    vars:
      INSTALLER_NAT_IP:
        sh: gcloud compute instances list --filter="evo-master" --format "get(networkInterfaces[0].accessConfigs[0].natIP)" --project {{.PROJECT_NAME}}
    cmds:
      - | 
        ssh -i {{.MNTDIR}}/gcp-evocloud.pem -o "StrictHostKeyChecking=no" {{.CLOUDUSER}}@{{.INSTALLER_NAT_IP}} \
          "ssh -i {{.HOMEDIR}}/gcp-evocloud.pem -o "StrictHostKeyChecking=no" {{.CLOUDUSER}}@{{.INSTALLER_NAT_IP}} \
          'gcloud auth activate-service-account --key-file {{.HOMEDIR}}/EVOCLOUD/Keys/{{.KEYFILE}} \
          && export GOOGLE_APPLICATION_CREDENTIALS="{{.HOMEDIR}}/EVOCLOUD/Keys/{{.KEYFILE}}" \
          && cd {{.HOMEDIR}}/EVOCLOUD/Terraform/gcp/deployment/cluster-talos-standalone/ && terragrunt apply -auto-approve'"
