version: 3

silent: true

# Creates Namespaces for tasks. To execute as task run the following:
# task gcp:build-evo-master
# task oci:build-evo-master
includes:
  gcp:
    taskfile: ./Terraform/gcp/Taskfile.yml
  oci:
    taskfile: ./Terraform/oci/Taskfile.yml
