---
#This playbook will deploy Toolhive-MCP
#References:

- ansible.builtin.debug:
    msg: "########### STARTING ANSIBLE ROLE: kubeapp-toolhive_mcp ##############"

- name: Creating directories for manifest files...
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ toolhive_kubeapp_dir }}"

######################################################
#Deploying Toolhive-MCP Resources
######################################################
- name: Staging Kubernetes manifests...
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ toolhive_kubeapp_dir }}/{{ item }}"
  loop:
    - toolhive-mcp-rset.yaml

- name: Deploying Kubernetes manifests...
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    src: "{{ item }}"
  loop:
    - "{{ toolhive_kubeapp_dir }}/toolhive-mcp-rset.yaml"
  register: toolhive_deploy_result
  until: toolhive_deploy_result is succeeded
  retries: 10
  delay: 30
