#--------------------------------------------------
# Guacamole Server VM
#--------------------------------------------------
locals {
  evovcd_cloud_init = <<-EOF
    #cloud-config
    write_files:
      - path: /etc/NetworkManager/dispatcher.d/ifup-local
        content: |
          #!/bin/sh
          nm-online -q --timeout=30
          if ! ip route show default | grep -q "via ${var.HCLOUD_GATEWAY}"; then
            /sbin/ip route add default via "${var.HCLOUD_GATEWAY}"
          fi
        permissions: '0755'

      - path: /etc/resolv.conf
        content: |
          # Generated by Cloud-init
          nameserver ${var.HCLOUD_METADATA_NS}
          nameserver ${var.HCLOUD_METADATA_NS2}

    runcmd:
      - dnf remove -y hc-utils #remove conflicting Hetzner auto-config
      - reboot
  EOF
}

data "hcloud_ssh_key" "public_key" {
  name       = "public-ssh-key"
}

resource "hcloud_server" "vcd_server" {
  name        = var.VCD_SHORT_HOSTNAME
  server_type = var.VCD_INSTANCE_SIZE
  location    = var.HCLOUD_REGION
  image       = var.BASE_AMI_NAME
  ssh_keys    = [data.hcloud_ssh_key.public_key.id]

  # This gets you an ipv4 primary ip
  public_net {
    ipv4_enabled = true
    ipv6_enabled = false
  }

  # Attach to private network
  network {
    network_id = var.dmz_subnet_id
    #There is a bug with Terraform 1.4+ which causes the network to be detached & attached on every apply. Set alias_ips = []
    alias_ips = [] #Bug: https://github.com/hetznercloud/terraform-provider-hcloud/issues/650#issuecomment-1497160625
  }

  user_data = local.evovcd_cloud_init

  #COME BACK HERE AND SET A FIREWALL RULE
  #firewall_ids = each.value.SECURITY_GROUP_IDS

}

#--------------------------------------------------
# Ansible Configuration Management Code
#--------------------------------------------------
#replacing null_resource with terraform_data
#https://developer.hashicorp.com/terraform/language/resources/terraform-data
resource "terraform_data" "trigger_redeploy" {
  input = var.vcd_revision
}

resource "terraform_data" "vcd_server_configuration" {
  depends_on = [hcloud_server.vcd_server]

  #Uncomment below if we want to run Triggers when VM ID changes
  #triggers_replace = [hcloud_server.vcd_server.id]
  #or Uncomment below if we want to run Triggers on Revision number increase
  lifecycle {
    replace_triggered_by = [terraform_data.trigger_redeploy]
  }

  provisioner "local-exec" {
    command = <<EOF
      ${var.ANSIBLE_DEBUG_FLAG ? "ANSIBLE_DEBUG=1" : ""} ANSIBLE_PIPELINING=True ansible-playbook --timeout 60 /${var.CLOUD_USER}/EVOCLOUD/Ansible/server-dmz-vcd.yml --forks 10 --inventory-file ${one(hcloud_server.vcd_server.network[*].ip)}, --user ${var.CLOUD_USER} --private-key ${var.PRIVATE_KEY_PAIR} --vault-password-file /${var.CLOUD_USER}/EVOCLOUD/Ansible/secret-vault/ansible-vault-pass.txt --ssh-common-args '-o 'StrictHostKeyChecking=no' -o 'ControlMaster=auto' -o 'ControlPersist=120s'' --extra-vars 'ansible_secret=/${var.CLOUD_USER}/EVOCLOUD/Ansible/secret-vault/secret-store.yml server_ip=${one(hcloud_server.vcd_server.network[*].ip)} idam_server_ip=${var.idam_server_ip} idam_short_hostname=${var.IDAM_SHORT_HOSTNAME} server_short_hostname=${var.VCD_SHORT_HOSTNAME} domain_tld=${var.DOMAIN_TLD} server_timezone=${var.DEFAULT_TIMEZONE} metadata_ns_ip=${var.HCLOUD_METADATA_NS} idam_replica_ip=${var.idam_replica_ip} cloud_platform=${var.CLOUD_PLATFORM}, san_ips=["${one(hcloud_server.vcd_server.network[*].ip)}", "${hcloud_server.vcd_server.ipv4_address}"] ports_list=[80,443]'
    EOF
    #Ansible logs
    environment = {
      ANSIBLE_LOG_PATH = "/${var.CLOUD_USER}/EVOCLOUD/Logs/server-dmz-vcd-ansible.log"
    }
  }
}