---
#This playbook will deploy Kyverno Policies
#References:

- ansible.builtin.debug:
    msg: "########### STARTING ANSIBLE ROLE: kubeapp-kyverno_policies ##############"

- name: Creating directories for manifest files...
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ kyverno_policies_kubeapp_dir }}"

######################################################
#Deploying Kyverno Policies Resources
######################################################
- name: Staging Kubernetes manifests...
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ kyverno_policies_kubeapp_dir }}/{{ item }}"
  loop:
    - kyverno-policies-rset.yaml

- name: Deploying Kubernetes manifests...
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    src: "{{ item }}"
  loop:
    - "{{ kyverno_policies_kubeapp_dir }}/kyverno-policies-rset.yaml"
  register: kyverno_pol_deploy_result
  until: kyverno_pol_deploy_result is succeeded
  retries: 10
  delay: 30
