---
#This playbook will deploy a DNS Record for the Kubernetes Application Endpoint
#References:

- ansible.builtin.debug:
    msg: "########### STARTING ANSIBLE ROLE: kubeapp-gateway-endpoint ##############"

- name: Staging directory for gateway-endpoints...
  ansible.builtin.file:
    path: "{{ kubeapp_dir }}/gateway-endpoints"
    state: directory

- name: Staging gateway-endpoint manifests...
  ansible.builtin.template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ kubeapp_shortname }}-{{ item.f }}'
  with_items:
    - f: 'gateway.yaml'
      d: "{{ kubeapp_dir }}/gateway-endpoints"
    - f: 'http-route.yaml'
      d: "{{ kubeapp_dir }}/gateway-endpoints"

- name: Deploying gateway and httproutes...
  ansible.builtin.shell: |
    KUBECONFIG={{ kubeconfig }} kubectl apply -f {{ item }}
  loop:
    - '{{ kubeapp_shortname }}-gateway.yaml'
    - '{{ kubeapp_shortname }}-http-route.yaml'
  args:
    executable: /bin/bash
    chdir: "{{ kubeapp_dir }}/gateway-endpoints"
