---
#This playbook will deploy the CSI External Snapshot Controller
#References: https://github.com/home-operations/helm-charts/tree/main/charts/snapshot-controller

- ansible.builtin.debug:
    msg: "########### STARTING ANSIBLE ROLE: kubeapp-snapshot_controller ##############"

- name: Creating directories for manifest files...
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ snapshot_controller_kubeapp_dir }}"

######################################################
#Deploying Snapshot Controller Resources
######################################################
- name: Staging Kubernetes manifests...
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ snapshot_controller_kubeapp_dir }}/{{ item }}"
  loop:
    - snapshot-controller-rset.yaml

- name: Deploying Kubernetes manifests...
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    src: "{{ item }}"
  loop:
    - "{{ snapshot_controller_kubeapp_dir }}/snapshot-controller-rset.yaml"
  register: snapshot_deploy_result
  until: snapshot_deploy_result is succeeded
  retries: 10
  delay: 30
