---
#This playbook will deploy Reloader Operator
#References:

- ansible.builtin.debug:
    msg: "########### STARTING ANSIBLE ROLE: kubeapp-reloader ##############"

- name: Creating directories for manifest files...
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ reloader_kubeapp_dir }}"

######################################################
#Deploying Reloader Operator Resources
######################################################
- name: Staging Kubernetes manifests...
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ reloader_kubeapp_dir }}/{{ item }}"
  loop:
    - reloader-rset.yaml

- name: Deploying Kubernetes manifests...
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    src: "{{ item }}"
  loop:
    - "{{ reloader_kubeapp_dir }}/reloader-rset.yaml"
  register: reloader_deploy_result
  until: reloader_deploy_result is succeeded
  retries: 10
  delay: 30
