---
#--------------------------------------------------------------
# COSIGN SPECIFIC VARS
#--------------------------------------------------------------
# Cosign Version
# renovate: datasource=github-releases depName=sigstore/cosign versioning=semver
cosign_version: "v3.1.3"

# Directory
cosign_dir: "/opt/cosign"

# Packages
cosign_binary: "cosign-linux-amd64"

# URLS: https://github.com/sigstore/cosign/releases/download/v3.1.3/cosign-linux-amd64
cosign_github_url: "https://github.com/sigstore/cosign/releases/download/{{ cosign_version }}"

#https://github.com/sigstore/cosign/releases/
# renovate: datasource=github-releases depName=sigstore/cosign packageName=cosign-linux-amd64
cosign_checksum: 'sha256:4629c757b7618056f8ddd7e2625ae9fdd94c0372a65049520bc7d9df9efc7f71'
