---
- ansible.builtin.debug:
    msg: "################# STARTING ANSIBLE ROLE: app-ansible ##################"

#Installs Ansible Configuration Management
- name: Installing Ansible packages...
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
    #update_cache: yes
  loop: "{{ required_packages }}"
  register: packages_install
  until: packages_install is succeeded
  retries: 3
  become: true

- name: Installing Ansible Posix Collection...
  ansible.builtin.shell: "/usr/bin/ansible-galaxy collection install ansible.posix"
  #become: true #Commented this out to enable installation of collection in /home/mlkroot/.ansible

- name: Installing Ansible Community.general Collection...
  ansible.builtin.shell: "/usr/bin/ansible-galaxy collection install community.general"
  #become: true #Commented this out to enable installation of collection in /home/mlkroot/.ansible

- name: Installing Ansible Community.mysql Collection...
  ansible.builtin.shell: "/usr/bin/ansible-galaxy collection install community.mysql"
  #become: true #Commented this out to enable installation of collection in /home/mlkroot/.ansible

- name: Copy ansible.cfg to /etc/ansible
  ansible.builtin.copy:
    src: "/tmp/ansible.cfg"
    dest: "/etc/ansible/ansible.cfg"
    owner: root
    group: root
    mode: '0644'
    remote_src: yes
  become: true

- name: Remove ansible.cfg in /tmp
  ansible.builtin.file:
    path: /tmp/ansible.cfg
    state: absent
  become: true