---
#This playbook will Cilium CLI Binary
#
#References:

- ansible.builtin.debug:
    msg: "################# STARTING ANSIBLE ROLE: app-cilium-cli ##################"

- name: Checking if cilium-cli already exist...
  ansible.builtin.stat:
    path: '{{ cilium_cli_install_dir }}/cilium'
  changed_when: false
  become: true
  register: cilium_cli_binary

- name: Uninstalling cilium-cli...
  ansible.builtin.file:
    path: '{{ cilium_cli_install_dir }}/cilium'
    state: absent
  become: true
  when: (cilium_cli_binary.stat.exists) and (cilium_cli_force_update | bool)

- when: (not cilium_cli_binary.stat.exists) or (cilium_cli_force_update | bool)
  block:
    - name: Verifying cilium-cli sha256 checksum...
      ansible.builtin.get_url:
        url: '{{ cilium_cli_download_url }}'
        dest: '/tmp'
        mode: '0644'
        checksum: '{{ cilium_cli_checksum }}'
      become: true

    - name: Installing Cilium-cli...
      ansible.builtin.unarchive:
        src: '/tmp/cilium-linux-amd64.tar.gz'
        dest: '{{ cilium_cli_install_dir }}'
        mode: '0755'
        remote_src: yes
      become: true

  always:
    - name: Removing cilium-cli detritus...
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - '/tmp/cilium-linux-amd64.tar.gz'
      become: true