---
- ansible.builtin.debug:
    msg: "################# STARTING ANSIBLE ROLE: server-nginx-proxy ##################"

# Installing nginx packages
- name: Installing nginx packages...
  ansible.builtin.dnf:
    name: '{{ nginx_package }}'
    state: present
    disable_gpg_check: yes
  register: nginx_install
  become: true

# Set SELinux boolean for nginx
- name: Setting SELinux booleans for nginx...
  ansible.posix.seboolean:
    name: "{{ item }}"
    state: yes
    persistent: yes
  loop:
    - httpd_can_network_connect
    - httpd_can_network_connect_db
    - httpd_setrlimit
  become: true

- name: Adding required ports to http_port_t...
  community.general.seport:
    ports: "{{ item }}"
    proto: tcp
    setype: http_port_t
    state: present
  with_items: "{{ ports_list }}"
  become: true

# Creating default virtualhost
- name: Configuring default virtualhost...
  ansible.builtin.template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
  become: true
  notify: Restarting webserver...

#Enable and start nginx
- name: Enabling and starting nginx...
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: true
  become: true

# Enable firewall rules
- name: Enabling firewall rules...
  ansible.posix.firewalld:
    port: "{{ item }}/tcp"
    permanent: yes
    immediate: yes
    state: enabled
  with_items: "{{ ports_list }}"
  become: true
