---
#This playbook will deploy DragonflyDB
#References:

- ansible.builtin.debug:
    msg: "########### STARTING ANSIBLE ROLE: kubeapp-dragonflydb ##############"

- name: Creating directories for manifest files...
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ dragonflydb_kubeapp_dir }}"

######################################################
#Deploying DragonflyDB Resources
######################################################
- name: Staging Kubernetes manifests...
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ dragonflydb_kubeapp_dir }}/{{ item }}"
  loop:
    - dragonflydb-rset.yaml

- name: Deploying Kubernetes manifests...
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    src: "{{ item }}"
  loop:
    - "{{ dragonflydb_kubeapp_dir }}/dragonflydb-rset.yaml"
  register: dragonflydb_deploy_result
  until: dragonflydb_deploy_result is succeeded
  retries: 10
  delay: 30
