---
#This playbook will deploy Kubevela
#References:

- ansible.builtin.debug:
    msg: "########### STARTING ANSIBLE ROLE: kubeapp-kubevela ##############"

- name: Creating directories for manifest files...
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ kubevela_kubeapp_dir }}"

######################################################
#Deploying Kubevela Resources
######################################################
- name: Staging Kubernetes manifests...
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ kubevela_kubeapp_dir }}/{{ item }}"
  loop:
    - kubevela-rset.yaml

- name: Deploying Kubernetes manifests...
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    src: "{{ item }}"
  loop:
    - "{{ kubevela_kubeapp_dir }}/kubevela-rset.yaml"
  register: kubevela_deploy_result
  until: kubevela_deploy_result is succeeded
  retries: 10
  delay: 30
