---
cloud_user: ""

domain_tld: ""

kube_cluster_name: ""

kubeapp_dir: '/home/{{ cloud_user }}/kubeapps/{{ kube_cluster_name }}'

kubeconfig: '/home/{{ cloud_user }}/kubeconfig/kubeconfig-{{ kube_cluster_name }}.yaml'

kubescape_kubeapp_dir: '{{ kubeapp_dir }}/kubescape'