---
#--------------------------------------------------------------
# COPA SPECIFIC VARS
#--------------------------------------------------------------
# Copa Version
# renovate: datasource=github-releases depName=project-copacetic/copacetic versioning=semver
copa_version: "0.14.2"

# Directory
copa_install_dir: "/usr/local/bin"

# Update flag
copa_force_update: false

# URLS: https://github.com/project-copacetic/copacetic/releases/download/v0.14.2/copa_0.14.2_linux_amd64.tar.gz
copa_download_url: "https://github.com/project-copacetic/copacetic/releases/download/v{{ copa_version }}/copa_{{ copa_version }}_linux_amd64.tar.gz"

#https://github.com/project-copacetic/copacetic/releases/
# renovate: datasource=github-releases depName=project-copacetic/copacetic packageName=copa-linux-amd64
copa_checksum: 'sha256:756c6e0f287dc7839c0a72e91b4d4712b1d8cd86a7233c068c0208a28bcb9ede'
