---
# renovate: datasource=github-releases depName=siderolabs/talos versioning=semver
talosctl_version: 'v1.13.9'

os_arch: 'linux-amd64'

talosctl_install_dir: /usr/local/bin

talosctl_force_update: false

#https://github.com/siderolabs/talos/releases/download/v1.13.9/talosctl-linux-amd64
talosctl_download_url: 'https://github.com/siderolabs/talos/releases/download/{{ talosctl_version }}/talosctl-{{ os_arch }}'

# https://github.com/siderolabs/talos/releases/download/v1.13.9/sha256sum.txt
# renovate: datasource=github-releases depName=siderolabs/talos packageName=talosctl-linux-amd64
talosctl_checksum: 'sha256:7e1d4b7d5846964bdcf63a794e3c8161bb6ef2983d5ace58ea5322f3bf32a27e'
