---
upstream_servers: '' #backend server IPs in comma separated with no space. ie: server1.ip,server2.ip

gateway_vip: '' #ipv4 of the gateway vip created during cluster deployment

zone: ''

ports_list: [] #This variable takes a list of port numbers

lb_node01_ip: ''

lb_node02_ip: ''

haproxy_version: '3.2.1'

haproxy_package: 'https://packages.zenetys.com/latest/redhat/8/RPMS/x86_64/haproxy32z-{{ haproxy_version }}-1.el8.zenetys.x86_64.rpm'

keepalive_packages:
  - keepalived
  - psmisc

net_interface: "eth0"

gateway_vip_cidr: "{{ gateway_vip }}/32"