---
#This playbook will deploy Kyverno
#References:

- ansible.builtin.debug:
    msg: "########### STARTING ANSIBLE ROLE: kubeapp-kyverno ##############"

- name: Creating directories for manifest files...
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ kyverno_kubeapp_dir }}"

######################################################
#Deploying Kyverno Resources
######################################################
- name: Staging Kubernetes manifests...
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ kyverno_kubeapp_dir }}/{{ item }}"
  loop:
    - kyverno-rset.yaml

- name: Deploying Kubernetes manifests...
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    src: "{{ item }}"
  loop:
    - "{{ kyverno_kubeapp_dir }}/kyverno-rset.yaml"
  register: kyverno_deploy_result
  until: kyverno_deploy_result is succeeded
  retries: 10
  delay: 30
