---
terraform_version: '1.13.3'

os_arch: linux_amd64

terraform_mirror: https://releases.hashicorp.com/terraform

terraform_install_dir: /usr/local/bin

terraform_provider_dir: /usr/share/terraform/providers/terraform.local/evocloud

terraform_force_update: false

# https://releases.hashicorp.com/terraform/1.13.3/terraform_1.13.3_SHA256SUMS
terraform_checksum: sha256:71fc43d92ea09907be5d416d2405a6a9c2d1ceaed633f5e175c0af26e8c4b365

terraform_zip: 'terraform_{{ terraform_version }}_{{ os_arch }}.zip'

# https://releases.hashicorp.com/terraform/1.13.3/terraform_1.13.3_linux_amd64.zip
terraform_download_url: '{{ terraform_mirror }}/{{ terraform_version }}/{{ terraform_zip }}'

terraform_binary_dir: '{{ terraform_install_dir }}/terraform_{{ terraform_version }}'

  