---
#--------------------------------------------------------------
# COMMON VARS
#--------------------------------------------------------------
domain_tld: ''

server_short_hostname: ''

server_ip: ''

idam_server_ip: ''

idam_replica_ip: ''

freeipa_admin_passwd: "{{ creds_store.freeipa_admin_passwd }}"
ldap_dc: "dc={{ domain_tld.split('.')[0] }},dc={{ domain_tld.split('.')[1] }}"

#--------------------------------------------------------------
# HARBOR SPECIFIC VARS
#--------------------------------------------------------------
# Harbor Version
harbor_version: "v2.14.0"

evoharbor_force_update: false

# Directories
cert_dir: '/etc/pki/host_certs'
docker_cert_dir: "/etc/docker/certs.d"
harbor_directory: "/opt/harbor"
harbor_cert_dir: "/data/cert"

# Harbor Password
harbor_admin_passwd: "{{ creds_store.code_harbor_passwd }}"

# Packages
harbor_installer: "harbor-online-installer-{{ harbor_version }}.tgz"

# URLS
harbor_github_url: "https://github.com/goharbor/harbor/releases/download"
harbor_url: "https://{{ server_short_name }}.{{ domain_tld }}"
