---
# renovate: datasource=github-releases depName=kubescape/kubescape versioning=semver
kubescape_ver: '4.0.12'

kubescape_install_dir: /usr/local/bin

kubescape_force_update: false

#https://github.com/kubescape/kubescape/releases/tag/v4.0.11
#https://github.com/kubescape/kubescape/releases/download/v4.0.11/kubescape_4.0.11_linux_amd64.tar.gz
kubescape_download_url: 'https://github.com/kubescape/kubescape/releases/download/v{{ kubescape_ver }}/kubescape_{{ kubescape_ver }}_linux_amd64.tar.gz'

# renovate: datasource=github-releases depName=kubescape/kubescape packageName=kubescape_4.0.11_linux_amd64.tar.gz
kubescape_checksum: 'sha256:5fef4b0b8a51751bf49bf079a9b62c3bfa0c6c56966cc9d470fa66909ace5123'
