---
#This playbook will deploy DocumentDB
#References:

- ansible.builtin.debug:
    msg: "########### STARTING ANSIBLE ROLE: kubeapp-documentdb ##############"

- name: Creating directories for manifest files...
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ documentdb_kubeapp_dir }}"

######################################################
#Deploying DocumentDB Resources
######################################################
- name: Staging Kubernetes manifests...
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ documentdb_kubeapp_dir }}/{{ item }}"
  loop:
    - documentdb-rset.yaml

- name: Deploying Kubernetes manifests...
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    src: "{{ item }}"
  loop:
    - "{{ documentdb_kubeapp_dir }}/documentdb-rset.yaml"
  register: documentdb_deploy_result
  until: documentdb_deploy_result is succeeded
  retries: 10
  delay: 30
