---
#This playbook will deploy ClusterSecret Operator
#References:

- ansible.builtin.debug:
    msg: "########### STARTING ANSIBLE ROLE: kubeapp-clustersecret ##############"

- name: Creating directories for manifest files...
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ clustersecret_kubeapp_dir }}"

######################################################
#Deploying ClusterSecret Operator Resources
######################################################
- name: Staging Kubernetes manifests...
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ clustersecret_kubeapp_dir }}/{{ item }}"
  loop:
    - clustersecret-rset.yaml

- name: Deploying Kubernetes manifests...
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    src: "{{ item }}"
  loop:
    - "{{ clustersecret_kubeapp_dir }}/clustersecret-rset.yaml"
  register: clustersecret_deploy_result
  until: clustersecret_deploy_result is succeeded
  retries: 10
  delay: 30
