---
#This playbook will deploy Rook Storage Cluster
#References:

- ansible.builtin.debug:
    msg: "########### STARTING ANSIBLE ROLE: kubeapp-rook ##############"

- name: Creating directories for manifest files...
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ kubeapp_dir }}/rook"

######################################################
#Deploying Rook Storage Cluster
######################################################
- name: Staging Kubernetes manifests...
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ kubeapp_dir }}/rook/{{ item }}"
  loop:
    - rook-rset.yaml

- name: Deploying Kubernetes manifests...
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    src: "{{ item }}"
  loop:
    - "{{ kubeapp_dir }}/rook/rook-rset.yaml"
  register: rook_deploy_result
  until: rook_deploy_result is succeeded
  retries: 4
  delay: 30
