---
sops_force_update: false

#https://github.com/getsops/sops/releases
sops_ver: 'v3.9.4'

#https://github.com/getsops/sops/releases/download/v3.9.4/sops-v3.9.4.linux.amd64
sops_download_url: 'https://github.com/getsops/sops/releases/download/{{ sops_ver }}/sops-{{ sops_ver }}.linux.amd64'

#https://github.com/getsops/sops/releases/download/v3.9.4/sops-v3.9.4.checksums.txt
sops_checksum: sha256:5488e32bc471de7982ad895dd054bbab3ab91c417a118426134551e9626e4e85

sops_install_dir: '/usr/local/bin'