---
#---------------------------------------------------------------------------------------
# This role will deploy Kubernetes Application Gateway API Endpoint
#---------------------------------------------------------------------------------------
- hosts: all
  gather_facts: false
  strategy: free
  vars:
    creds_store: "{{ lookup('file', ansible_secret) | from_yaml }}"

  roles:
    - kubeapp-gateway-endpoint
