---
#----------------------------------------------------
# This role will configure the Apache Guacamole VCD
#----------------------------------------------------

- hosts: all
  gather_facts: false
  strategy: free
  vars:
    creds_store: "{{ lookup('file', ansible_secret) | from_yaml }}"

  roles:
    - app-dnsmasq #Needed by GCP Compute Instances
    - config-freeipa-client
    - config-freeipa-certs
    - app-openjdk
    - server-tomcat #requires app-openjdk
    - server-guacamole-postgres
    - server-nginx-proxy
    - server-guacamole
    - app-fail2ban