---
#--------------------------------------------------
# This role will configure the deployer server
#--------------------------------------------------
- hosts: all
  gather_facts: false
  strategy: free
  roles:
    - app-clamav
    - app-terraform
    - app-packer
    - app-vault
    - app-terragrunt
    - app-kubectl
    - app-kubelogin
    - app-kubescape
    - app-helm
    - app-cilium-cli
    - app-hubble-cli
    - app-flux-cli
    - app-talos-cli
    - app-age
    - app-sops
    - app-ansible
    - app-trivy
    - app-kubelint
    - app-nerdctl
    - app-cosign
    - app-fail2ban