---
#--------------------------------------------------
# This role creates EvoCode Group and Project
#--------------------------------------------------
- hosts: all
  gather_facts: false
  strategy: free
  vars:
    creds_store: "{{ lookup('file', ansible_secret) | from_yaml }}"

  roles:
    - webapp-evocode-group-project