---
#################################################################
# This role configures evo-master server to join the IDP Server
################################################################
- hosts: all
  gather_facts: false
  strategy: free
  vars:
    creds_store: "{{ lookup('file', ansible_secret) | from_yaml }}"

  roles:
    - app-dnsmasq #Needed by GCP Compute Instances
    - config-freeipa-client
    - config-freeipa-certs
