---
#--------------------------------------------------
# This role will configure the deployer server
#--------------------------------------------------
- hosts: all
  gather_facts: false

  roles:
    - app-clamav
    - app-terraform
    - app-packer
    - app-vault
    - app-terragrunt
    - app-kubectl
    - app-helm
    - app-cilium-cli
    #- app-hubble-cli
    #- app-flux-cli
    - app-ansible
    - app-trivy
    - app-kubelint
    - app-nerdctl
    - app-fail2ban