---
#------------------------------------------------------
# This role deploys EvoCode Enterprise Code Repository
#------------------------------------------------------
- hosts: all
  gather_facts: false
  strategy: linear
  vars:
    creds_store: "{{ lookup('file', ansible_secret) | from_yaml }}"

  roles:
    - app-dnsmasq #Needed by GCP Compute Instances
    - config-freeipa-client
    - config-freeipa-certs
    - webapp-evocode
    - app-fail2ban