---
#############################################
#DEPLOYING Talos Upgrade Operator
#############################################
#Reference: https://github.com/home-operations/tuppr/tree/main/charts/tuppr
#           https://github.com/home-operations/tuppr/tree/main/charts/tuppr

# https://kubernetes-schemas.pages.dev/fluxcd.controlplane.io/resourceset_v1.json
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: talos-upgrade-operator
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "1h"
    fluxcd.controlplane.io/reconcileTimeout: "20m"
spec:
  dependsOn:
    - apiVersion: fluxcd.controlplane.io/v1
      kind: FluxInstance
      name: flux
      namespace: flux-system
      ready: true
    # Add dependsOn storageClass
    # Add dependsOn Monitoring Stack

  resources:
    #- apiVersion: v1
    #  kind: Namespace
    #  metadata:
    #    name: talos-system-upgrade

    #https://github.com/fluxcd-community/flux2-schemas/blob/main/ocirepository-source-v1.json
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: OCIRepository
      metadata:
        name: talos-upgrade-operator
        namespace: flux-system
      spec:
        interval: 12h
        url: oci://ghcr.io/home-operations/charts/tuppr
        layerSelector:
          mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
          operation: copy
        ref:
          semver: "0.2.*"

    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: talos-upgrade-operator
        namespace: kube-system
      spec:
        #serviceAccountName: talos-upgrade-operator-sa
        chartRef:
          kind: OCIRepository
          name: talos-upgrade-operator
          namespace: flux-system
        interval: 30m
        timeout: 15m0s
        install:
          remediation:
            retries: 3
        upgrade:
          remediation:
            retries: 2
        driftDetection:
          mode: enabled
        values:
          replicaCount: 1
          controller:
            logLevel: info
          #Set below to true if kube prometheus stack is deployed
          monitoring:
            serviceMonitor:
              enabled: true
            prometheusRule:
              enabled: false
            dashboards:
              enabled: true
              grafanaOperator:
                enabled: false
                matchLabels:
                  dashboards: grafana