---
#This playbook will deploy Trivy Operator
#References:

- ansible.builtin.debug:
    msg: "########### STARTING ANSIBLE ROLE: kubeapp-trivy ##############"

- name: Creating directories for manifest files...
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ trivy_kubeapp_dir }}"

######################################################
#Deploying Trivy Operator Resources
######################################################
- name: Staging Kubernetes manifests...
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ trivy_kubeapp_dir }}/{{ item }}"
  loop:
    - trivy-rset.yaml

- name: Deploying Kubernetes manifests...
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    src: "{{ item }}"
  loop:
    - "{{ trivy_kubeapp_dir }}/trivy-rset.yaml"
  register: trivy_deploy_result
  until: trivy_deploy_result is succeeded
  retries: 10
  delay: 30
