---
#This playbook will deploy Cilium Gateway
#References:

- ansible.builtin.debug:
    msg: "########### STARTING ANSIBLE ROLE: kubeapp-cilium-gateway ##############"

- name: Creating directories for manifest files...
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ kubeapp_dir }}/cilium-gateway"

######################################################
#Deploying Cilium Gateway Resource
######################################################
- name: Staging Kubernetes manifests...
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ kubeapp_dir }}/cilium-gateway/{{ item }}"
  loop:
    - cilium-gateway.yaml

- name: Deploying Kubernetes manifests...
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    src: "{{ item }}"
  loop:
    - "{{ kubeapp_dir }}/cilium-gateway/cilium-gateway.yaml"
  register: gateway_deploy_result
  until: gateway_deploy_result is succeeded
  retries: 10
  delay: 30
