---
cloud_user: ""

kube_cluster_name: ""

kubeapp_dir: '/home/{{ cloud_user }}/kubeapps/{{ kube_cluster_name }}'

kubeconfig: '/home/{{ cloud_user }}/kubeconfig/kubeconfig-{{ kube_cluster_name }}.yaml'
